language: python

sudo: false

dist: trusty
group: edge

python:
   - "3.6"
   - "3.7"

os:
  - linux


install:
  - pip install --upgrade pip
  - pip install -e .

script:
  - "python setup.py test || exit 0" 
  - "python setup.py test"
